# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('instructions', models.CharField(max_length=10000)),
                ('duration', models.DurationField()),
                ('s_time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(default=b'3f59f4c0-26a8-11e6-a363-6cc217e9b519', max_length=50)),
                ('q_des', models.CharField(max_length=1000)),
                ('c1', models.CharField(max_length=500)),
                ('c2', models.CharField(max_length=500)),
                ('c3', models.CharField(max_length=500)),
                ('c4', models.CharField(max_length=500)),
                ('correct', models.CharField(choices=[('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4')], max_length=50)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.paper')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField()),
                ('all_papers', models.CharField(max_length=50, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
        migrations.AddField(
            model_name='paper',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
