# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'211f0b70-26a9-11e6-bb9d-6cc217e9b519', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='all_papers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
