# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20160531_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'0c8d6ce1-2818-11e6-bbb8-6cc217e9b519', max_length=50),
        ),
        migrations.AddField(
            model_name='paper',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, to='tests.section'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.section'),
        ),
    ]
