# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20160601_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='e_user',
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'422a90de-281c-11e6-b958-6cc217e9b519', max_length=50),
        ),
    ]
