# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20160601_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'6e1abc21-281c-11e6-9aec-6cc217e9b519', max_length=50),
        ),
    ]
