# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20160601_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='p_id',
            field=models.CharField(default=b'05378280-281f-11e6-b1bb-6cc217e9b519', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'05378281-281f-11e6-b342-6cc217e9b519', max_length=50),
        ),
    ]
