# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20160601_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='p_id',
            field=models.CharField(default=b'5ebb01b0-281f-11e6-8714-6cc217e9b519', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'5ebb01b1-281f-11e6-96f4-6cc217e9b519', max_length=50, unique=True),
        ),
    ]
