# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20160601_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='p_id',
            field=models.CharField(default=b'77f6761c-c339-45b2-821f-735fe0fa9a8a', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'3d6b654d-3ccd-4cc5-bf1e-144a9bb680b0', max_length=50, unique=True),
        ),
    ]
