# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20160601_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='p_id',
            field=models.CharField(default=b'<function uuid1 at 0x02EE4CB0>', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(default=b'<function uuid1 at 0x02EE4CB0>', max_length=50, unique=True),
        ),
    ]
