# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20160601_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='p_name',
            field=models.CharField(default='paper', max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='p_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
