# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20160602_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='p_name',
            field=models.CharField(max_length=50),
        ),
    ]
