# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20160602_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
