# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_remove_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='e_time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 4, 23, 21, 55, 376000)),
        ),
    ]
