# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_paper_e_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='e_time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 5, 15, 19, 1, 681000)),
        ),
        migrations.AddField(
            model_name='result',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.paper'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.e_user'),
        ),
    ]
