# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 09:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20160605_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='e_time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 5, 15, 19, 55, 683000)),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
