# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20160605_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='e_time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 6, 3, 18, 48, 313000)),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_des',
            field=models.TextField(max_length=1000),
        ),
    ]
